 /* ============================================================================
   CRM
   ============================================================================ */

CREATE SCHEMA IF NOT EXISTS CRM;

create or replace TABLE KPH_VERTEX_PRD.CRM.USERS (
	SYSTEMUSERID VARCHAR(16777216) NOT NULL DEFAULT UUID_STRING(),
	ACCESSMODE VARCHAR(255),
	CREATEDON TIMESTAMP_NTZ(9),
	EMAILADDRESS VARCHAR(128),
	FIRSTNAME VARCHAR(255),
	ISDISABLED VARCHAR(255),
	ISINTEGRATIONUSER VARCHAR(255),
	ISLICENSED VARCHAR(255),
	JOBTITLE VARCHAR(255),
	LASTNAME VARCHAR(255),
	MIDDLENAME VARCHAR(255),
	MODIFIEDBY VARCHAR(16777216),
	MODIFIEDON TIMESTAMP_NTZ(9),
	TITLE VARCHAR(255),
	USERNAME VARCHAR(128), --This is version 2
	constraint PK_USERS primary key (SYSTEMUSERID)
);

 /* ============================================================================
   VERTEX
   ============================================================================ */

create or replace sequence KPH_VERTEX_PRD.VERTEX.SEQ_COPAY_SOURCEFILES start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.VERTEX.SEQ_PROCESS_STATUSBYSOURCEFILE start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.VERTEX.SEQ_SOURCEFILES start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.VERTEX.SEQ_SYSTEMSETTINGS start with 1 increment by 1 noorder;

create or replace TABLE KPH_VERTEX_PRD.VERTEX.COPAY_SOURCEFILES (
	SOURCEFILEID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.VERTEX.SEQ_COPAY_SOURCEFILES.NEXTVAL,
	PROGRAMID NUMBER(38,0),
	FILENAME VARCHAR(99),
	LOADDATE TIMESTAMP_NTZ(9),
	ENTEREDBY VARCHAR(75) NOT NULL DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) NOT NULL DEFAULT CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ(9)),
	RECORDCOUNT NUMBER(38,0),
	primary key (SOURCEFILEID)
);

create or replace TABLE KPH_VERTEX_PRD.VERTEX.PROCESS_STATUSBYSOURCEFILE (
	ID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.VERTEX.SEQ_PROCESS_STATUSBYSOURCEFILE.NEXTVAL,
	PROCESSTYPEID NUMBER(38,0) NOT NULL,
	SOURCEFILEID NUMBER(38,0) NOT NULL,
	PASSEDVALIDATION BOOLEAN NOT NULL DEFAULT TRUE,
	MAILITEMID_FAIL NUMBER(38,0),
	MAILITEMID_PASS NUMBER(38,0),
	ENTEREDBY VARCHAR(75) NOT NULL DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) NOT NULL DEFAULT CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ(9)),
	primary key (ID)
);

create or replace TABLE KPH_VERTEX_PRD.VERTEX.SOURCEFILES (
	SOURCEFILEID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.VERTEX.SEQ_SOURCEFILES.NEXTVAL,
	FILECATEGORYID NUMBER(38,0),
	PARTNERID NUMBER(38,0),
	FILENAME VARCHAR(255),
	FILEDATE TIMESTAMP_NTZ(9),
	IMPORTDATE TIMESTAMP_NTZ(9) DEFAULT CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ(9)),
	RECORDCOUNT NUMBER(38,0),
	ORIGINALFILENAME VARCHAR(128),
	RECORDCOUNTS_STAGING NUMBER(38,0),
	RECORDCOUNTS_WK_TABLE NUMBER(38,0),
	RECORDCOUNTS_HS_TABLE NUMBER(38,0),
	RECORDCOUNTS_PASSEDRECORDS NUMBER(38,0),
	RECORDCOUNTS_FAILEDRECORDS NUMBER(38,0),
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ(9)),
	PROCESSED BOOLEAN DEFAULT FALSE,
	PROCESSEDTIME TIMESTAMP_NTZ(9),
	primary key (SOURCEFILEID)
);

create or replace TABLE KPH_VERTEX_PRD.VERTEX.SYSTEMSETTINGS (
	SYSTEMSETTINGID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	SERVERNAME VARCHAR(32),
	EMAILADDRESS VARCHAR(64),
	ROOTDIRECTORY VARCHAR(128),
	IDCARDPRODUCTION VARCHAR(128),
	REFERENCELISTING VARCHAR(128),
	CVSFORMULARYDIRECTORY VARCHAR(128),
	CRMBENEFITLOAD VARCHAR(128),
	INVOICEDIRECTORY VARCHAR(128),
	DISCOUNTCARDDIRECTORY VARCHAR(128),
	CRMSERVERURL VARCHAR(128),
	CRMAPPID VARCHAR(64),
	CRMSECRET VARCHAR(64),
	SHAREPOINT_URL VARCHAR(200),
	SHAREPOINT_TOKENPATH VARCHAR(255),
	SHAREPOINT_TOKENPASSWORD VARCHAR(40),
	constraint PK_SYSTEMSETTINGS primary key (SYSTEMSETTINGID)
);

INSERT INTO KPH_VERTEX_PRD.VERTEX.SYSTEMSETTINGS(SERVERNAME, EMAILADDRESS, ROOTDIRECTORY,IDCARDPRODUCTION, REFERENCELISTING)
VALUES ('KPHS-DBSRV03','jaimechapman@kphhealthcareservices.com','\\\\KNYGNAS\\Common\\MicroStrategy\\','\\\\kphs-dbsrv03\\ID Card Production\\','\\\\KNYGNAS\Common\\MicroStrategy\\');


CREATE OR REPLACE PROCEDURE KPH_VERTEX_PRD.VERTEX.GETSYSTEMSETTINGS()
RETURNS TABLE ("EMAILADDRESS" VARCHAR, "SERVER" VARCHAR, "DIRECTORY" VARCHAR, "CRMINSTANCE" VARCHAR)
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_EMAILADDRESS VARCHAR DEFAULT NULL;
    V_SERVER       VARCHAR DEFAULT NULL;
    V_DIRECTORY    VARCHAR DEFAULT NULL;
    V_CRMINSTANCE  VARCHAR DEFAULT NULL;
    RES            RESULTSET;
BEGIN
----------------------------------------------------------------------------
-- Get EmailAddress from CRM.USERS
----------------------------------------------------------------------------
    SELECT EMAILADDRESS INTO :V_EMAILADDRESS
    FROM CRM.USERS --Change this to point to CRM schema
    ORDER BY USERNAME
    LIMIT 1;

----------------------------------------------------------------------------
-- Get settings from CRM.SYSTEMSETTINGS
----------------------------------------------------------------------------
    SELECT SERVERNAME, ROOTDIRECTORY, COALESCE(EMAILADDRESS, :V_EMAILADDRESS)
    INTO  :V_SERVER, :V_DIRECTORY, :V_EMAILADDRESS
    FROM VERTEX.SYSTEMSETTINGS;

----------------------------------------------------------------------------
-- Build resultset and return it
----------------------------------------------------------------------------
    RES := (
        SELECT
              :V_EMAILADDRESS AS EMAILADDRESS
            , :V_SERVER       AS SERVER
            , :V_DIRECTORY    AS DIRECTORY
            , :V_CRMINSTANCE  AS CRMINSTANCE
    );

    RETURN TABLE(RES);
END;
$$;

CREATE OR REPLACE PROCEDURE KPH_VERTEX_PRD.VERTEX.SPINSERT_SOURCEFILE("VFILECATEGORYID" NUMBER(38,0), "VPARTNERID" NUMBER(38,0), "VFILENAME" VARCHAR, "VFILEDATE" DATE DEFAULT null, "VIMPORTDATE" TIMESTAMP_NTZ(9) DEFAULT null, "VORIGINALFILENAME" VARCHAR DEFAULT null)
RETURNS NUMBER(38,0)
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    SP_NAME STRING DEFAULT 'VERTEX.SPINSERT_SOURCEFILE';
    SP_START_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;
    V_SOURCEFILEID NUMBER(38,0);
BEGIN
    BEGIN TRANSACTION;

    -- Get the next key from a sequence
    SELECT VERTEX.SEQ_SOURCEFILES.NEXTVAL
      INTO :V_SOURCEFILEID;

    -- Insert the row
    INSERT INTO VERTEX.SOURCEFILES
    (
        SOURCEFILEID,
        FILECATEGORYID,
        PARTNERID,
        FILENAME,
        FILEDATE,
        IMPORTDATE,
        ORIGINALFILENAME
    )
    VALUES
    (
        :V_SOURCEFILEID,
        :VFILECATEGORYID,
        :VPARTNERID,
        :VFILENAME,
        :VFILEDATE,
        COALESCE(:VIMPORTDATE, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ),
        :VORIGINALFILENAME
    );

    COMMIT;

    -- Audit log
    INSERT INTO METRICS.SP_CALL
    (
        SP_NAME,
        SP_START_TIME,
        SP_USER,
        SP_END_TIME
    )
    VALUES
    (
        :SP_NAME,
        :SP_START_TIME,
        CURRENT_USER(),
        CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
    );

    RETURN V_SOURCEFILEID;

EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;

        INSERT INTO STAGE.SP_CALL
        (
            SP_NAME,
            SP_START_TIME,
            SP_USER,
            SP_END_TIME
        )
        VALUES
        (
            :SP_NAME || ' - FAILED',
            :SP_START_TIME,
            CURRENT_USER(),
            CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
        );

        RAISE;
END;
$$;

CREATE OR REPLACE PROCEDURE KPH_VERTEX_PRD.VERTEX.SP_MANAGE_SOURCEFILE("VREQUESTTYPE" NUMBER(38,0), "VFILENAME" VARCHAR DEFAULT null, "VFILECATEGORYID" NUMBER(38,0) DEFAULT null, "VSOURCEFILEID" NUMBER(38,0) DEFAULT null, "VRECORDCOUNT" NUMBER(38,0) DEFAULT null)
RETURNS NUMBER(1,0)
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    SP_NAME STRING DEFAULT 'SP_MANAGE_SOURCEFILE';
    SP_START_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;
    V_EXISTS_COUNT BOOLEAN DEFAULT 0;
    V_RESULT VARIANT DEFAULT NULL;
BEGIN
    BEGIN TRANSACTION;

    -- =========================================================================================
    -- REQUEST TYPE 1
    -- Check whether the source file already exists for the supplied file category.
    -- =========================================================================================
    IF (VREQUESTTYPE = 1) THEN

        SELECT COUNT(1)
          INTO :V_EXISTS_COUNT
          FROM VERTEX.SOURCEFILES
         WHERE FILENAME = :VFILENAME
           AND FILECATEGORYID = :VFILECATEGORYID;

        V_RESULT := OBJECT_CONSTRUCT(
            'STATUS', 'SUCCESS',
            'REQUEST_TYPE', 1,
            'RECORD_COUNT', V_EXISTS_COUNT
        );

    -- =========================================================================================
    -- REQUEST TYPE 2
    -- Update record count in SOURCEFILES.
    -- =========================================================================================
    ELSEIF (VREQUESTTYPE = 2) THEN

        UPDATE VERTEX.SOURCEFILES
           SET RECORDCOUNT = COALESCE(:VRECORDCOUNT, 0)
         WHERE SOURCEFILEID = :VSOURCEFILEID;

        V_RESULT := OBJECT_CONSTRUCT(
            'STATUS', 'SUCCESS',
            'REQUEST_TYPE', 2,
            'SOURCE_FILE_ID', VSOURCEFILEID
        );

    -- =========================================================================================
    -- REQUEST TYPE 3
    -- Delete child rows first, then parent row.
    -- =========================================================================================
    ELSEIF (VREQUESTTYPE = 3) THEN

        DELETE FROM VERTEX.PROCESS_STATUSBYSOURCEFILE
         WHERE SOURCEFILEID = :VSOURCEFILEID;

        DELETE FROM VERTEX.SOURCEFILES
         WHERE SOURCEFILEID = :VSOURCEFILEID;

        V_RESULT := OBJECT_CONSTRUCT(
            'STATUS', 'SUCCESS',
            'REQUEST_TYPE', 3,
            'SOURCE_FILE_ID', VSOURCEFILEID
        );

    -- =========================================================================================
    -- REQUEST TYPE 4
    -- Update record count in COPAY.SOURCEFILES.
    -- =========================================================================================
    ELSEIF (VREQUESTTYPE = 4) THEN

        UPDATE VERTEX.copay_SOURCEFILES
           SET RECORDCOUNT = COALESCE(:VRECORDCOUNT, 0)
         WHERE SOURCEFILEID = :VSOURCEFILEID;

        V_RESULT := OBJECT_CONSTRUCT(
            'STATUS', 'SUCCESS',
            'REQUEST_TYPE', 4,
            'SOURCE_FILE_ID', VSOURCEFILEID
        );

    -- =========================================================================================
    -- INVALID REQUEST TYPE
    -- =========================================================================================
    ELSE

        V_RESULT := OBJECT_CONSTRUCT(
            'STATUS', 'FAILED',
            'MESSAGE', 'Invalid VREQUESTTYPE. Valid values are 1, 2, 3, and 4.'
        );

    END IF;

    COMMIT;

    -- =========================================================================================
    -- AUDIT LOG
    -- =========================================================================================
    INSERT INTO METRICS.SP_CALL
    (
        SP_NAME,
        SP_START_TIME,
        SP_USER,
        SP_END_TIME
    )
    VALUES
    (
        :SP_NAME,
        :SP_START_TIME,
        CURRENT_USER(),
        CURRENT_TIMESTAMP()
    );

    RETURN IFF(V_EXISTS_COUNT, 1, 0);
	
	--RETURN V_EXISTS_COUNT;

EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;

        -- Best-effort audit entry for failures using the existing SP_CALL table design.
        INSERT INTO VERTEX.SP_CALL
        (
            SP_NAME,
            SP_START_TIME,
            SP_USER,
            SP_END_TIME
        )
        VALUES
        (
            :SP_NAME || ' - FAILED',
            :SP_START_TIME,
            CURRENT_USER(),
            CURRENT_TIMESTAMP()
        );

        RAISE;
END;
$$;

 /* ============================================================================
   METRICS
   ============================================================================ */

CREATE SCHEMA METRICS;

create or replace sequence KPH_VERTEX_PRD.METRICS.SEQ_SP_CALL start with 1 increment by 1 noorder;

create or replace TABLE KPH_VERTEX_PRD.METRICS.SP_CALL (
	SP_CALL_ID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.METRICS.SEQ_SP_CALL.NEXTVAL,
	SP_NAME VARCHAR(150) NOT NULL,
	SP_USER VARCHAR(100) NOT NULL,
	SP_START_TIME TIMESTAMP_NTZ(9) NOT NULL,
	SP_END_TIME TIMESTAMP_NTZ(9),
	ENTEREDBY VARCHAR(75) NOT NULL DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	primary key (SP_CALL_ID)
);

 /* ============================================================================
   STAGE
   ============================================================================ */

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPANAWPPRICES (
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	AWPINDICATORCODE VARCHAR(1),
	AWPPACKAGEPRICE VARCHAR(10),
	AWPUNITPRICE VARCHAR(13),
	EFFECTIVEDATE VARCHAR(8),
	OLDERAWPPACKAGEPRICE VARCHAR(10),
	OLDERAWPUNITPRICE VARCHAR(13),
	OLDERAWPEFFECTIVEDATE VARCHAR(8),
	RESERVE VARCHAR(16),
	LASTCHANGEDATE VARCHAR(5)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPANCMSFULPRICES (
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	RESERVE1 VARCHAR(1),
	CMSFULPRICE VARCHAR(13),
	CMSFULPRICEEFFECTIVEDATE VARCHAR(8),
	FIRSTOLDESTCMSFULPRICE VARCHAR(13),
	FIRSTOLDESTCMDFULPRICEEFFECTIVEDATE VARCHAR(8),
	SECONDOLDESTCMSFULPRICE VARCHAR(13),
	SECONDOLDESTCMSFULPRICEEFFECTIVEDATE VARCHAR(8),
	RESERVE2 VARCHAR(15),
	LASTCHANGEDATE VARCHAR(5)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPANGENERICPRODUCTS (
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	GENERICPRODUCTIDENTIFIER VARCHAR(14),
	RESERVE VARCHAR(5),
	GPIGENERICNAME VARCHAR(60),
	LASTCHANGEDATE VARCHAR(5)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPANINGREDIENTS (
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	INGREDIENTGENERIDIDTYPECODE VARCHAR(1),
	INGREDIENTGENERICIDNUMBER VARCHAR(9),
	INGREDIENTSTRENGTH VARCHAR(13),
	INGREDIENTUNITOFMEASURE VARCHAR(11),
	GENERICINGREDIENTNAME VARCHAR(40),
	ACTIVEINACTIVEINGREDIENTFLAG VARCHAR(4),
	RESERVE VARCHAR(4),
	LASTCHANGEDATE VARCHAR(5)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPANKEYIDENTIFIERS (
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	SEQUENCECODE VARCHAR(7),
	LABELERCODE VARCHAR(5),
	GENERICIDTYPECODE VARCHAR(1),
	GENERICIDNUMBER VARCHAR(9),
	DEACLASSCODE VARCHAR(5),
	AFHSTHERAPEUTICCLASSCODE VARCHAR(6),
	ITEMSTATUSFLAG VARCHAR(1),
	LOCALSYSTEMATICFLAG VARCHAR(1),
	TEECODE VARCHAR(2),
	FORMATTEDIDNUMBER VARCHAR(13),
	RXOTCINDICATOR VARCHAR(1),
	THIRDPARTYRESTRICTIONCODE VARCHAR(1),
	MAINTENANCEDRUGCODE VARCHAR(1),
	DISPENSINGUNITCODE VARCHAR(1),
	UNITDOSECODE VARCHAR(1),
	ROUTEOFADMINISTRATION VARCHAR(2),
	FORMTYPECODE VARCHAR(1),
	DOLLARRANKCODE VARCHAR(1),
	RXRANKCODE VARCHAR(1),
	NUMBERSYSTEMCHARACTER VARCHAR(1),
	SECONDARYFORMATIDCODE VARCHAR(1),
	SECONDARYIDNUMBER VARCHAR(10),
	MULTISOURCECODE VARCHAR(1),
	BRANDNAMECODE VARCHAR(1),
	RESERVE1 VARCHAR(1),
	INTERNALEXTERNALCODE VARCHAR(1),
	SINGLECOMINATIONCODE VARCHAR(1),
	STORAGECONDITIONCODE VARCHAR(1),
	LIMITEDSTATIBILITYCODE VARCHAR(1),
	LASTCHANGEDATE VARCHAR(5)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPANMANUFACTURERNAMES (
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	MANUFACTURERSNAME VARCHAR(30),
	MANUFACTURERSABBREVIATEDNAME VARCHAR(10),
	PRODUCTDESCRIPTIONABBREVIATION VARCHAR(25),
	DRUGNAMECODE VARCHAR(6),
	GENERICPRODUCTPACKAGINGCODE VARCHAR(8),
	LASTCHANGEDATE VARCHAR(5)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPANMANUFACTURERSDPMASTERS (
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	RESERVE VARCHAR(1),
	DPPACKAGEPRICE VARCHAR(10),
	DPUNITPRICE VARCHAR(13),
	EFFECTIVEDATE VARCHAR(8),
	OLDERDPPACKAGEPRICE VARCHAR(10),
	OLDERDPUNITPRICE VARCHAR(13),
	OLDERDPEFFECTIVEDATE VARCHAR(8),
	RESERVE2 VARCHAR(16),
	LASTCHANGEDATE VARCHAR(5)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPANNEWOLDNDCS (
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	OLDNDC VARCHAR(11),
	RESERVE1 VARCHAR(1),
	OLDFORMATTEDIDNUMBER VARCHAR(13),
	OLDEFFECTIVEDATE VARCHAR(5),
	NEWNDC VARCHAR(11),
	RESERVE2 VARCHAR(1),
	NEWFORMATTEDIDNUMBER VARCHAR(13),
	NEWEFFECTIVEDATE VARCHAR(5),
	RESERVE3 VARCHAR(19),
	LASTCHANGEDATE VARCHAR(5)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPANPACKAGINGEXTENSIONS (
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	METRICSTRENGTH VARCHAR(13),
	STRENGTHUNITOFMEASURE VARCHAR(11),
	LIMITEDDISCRIBUTIONCODE VARCHAR(2),
	EXTENDEDAHFSTHERAPEUTICCLASSCODE VARCHAR(8),
	INACTIVEDATE VARCHAR(8),
	RESERVE VARCHAR(37),
	LASTCHANGEDATE VARCHAR(16777216)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPANPACKAGINGS (
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	RESERVE1 VARCHAR(23),
	DOSAGEFORM VARCHAR(4),
	PACKAGESIZE VARCHAR(8),
	PACKAGESIZEUNITOFMEASURE VARCHAR(2),
	PACKAGEQUANTITY VARCHAR(5),
	REPACKAGECODE VARCHAR(1),
	TOTALPACKAGEQUANTITY VARCHAR(12),
	DESICODE VARCHAR(1),
	PACKAGEDESCRIPTION VARCHAR(10),
	RESERVE2 VARCHAR(6),
	NEXTSMALLERNDCSUFFIXNUMBER VARCHAR(2),
	NEXTLARGETNDCSUFFIXNUMBER VARCHAR(2),
	INNERPACKCODE VARCHAR(1),
	CLINICPACKCODE VARCHAR(1),
	RESERVE3 VARCHAR(1),
	LASTCHANGEDATE VARCHAR(5)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPANPRODUCTNAMES (
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	PRODUCTNAME VARCHAR(25),
	PRODUCTNAMEEXTENSION VARCHAR(35),
	RESERVE1 VARCHAR(8),
	ALLERGYPATTERNCODE VARCHAR(4),
	RESERVE2 VARCHAR(2),
	PPGINDICATORCODE VARCHAR(1),
	HFPGINDICATORCODE VARCHAR(1),
	LABELERTYPECODE VARCHAR(1),
	PRICINGSPREADCODE VARCHAR(1),
	RESERVE3 VARCHAR(1),
	LASTCHANGEDATE VARCHAR(5)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPANWACPRICES (
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	RESERVE1 VARCHAR(1),
	WACPACKAGEPRICE VARCHAR(10),
	WACUNITPRICE VARCHAR(13),
	EFFECTIVEDATE VARCHAR(8),
	OLDERWACPACKAGEPRICE VARCHAR(10),
	OLDERWACUNITPRICE VARCHAR(13),
	OLDERWACEFFECTIVEDATE VARCHAR(8),
	RESERVE2 VARCHAR(16),
	LASTCHANGEDATE VARCHAR(5)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPAN_M25DICT_DICTIONARY (
	SOURCEFILEID NUMBER(38,0),
	SOURCEFILELINENUMBER NUMBER(38,0),
	FIELD_IDENTIFIER VARCHAR(255),
	FIELD_VALUE VARCHAR(255),
	FIELD_TYPE VARCHAR(15),
	FIELD_LENGTH NUMBER(15,0),
	IMPLIED_DECIMAL_FLAG VARCHAR(1),
	DECIMAL_PLACES VARCHAR(5),
	FIELD_VALIDATION_FLAG VARCHAR(1),
	FIELD_ABBREVIATION_FLAG VARCHAR(1),
	RESERVE VARCHAR(255)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPAN_M25GPPC_GPPC (
	SOURCEFILEID NUMBER(38,0),
	SOURCEFILELINENUMBER NUMBER(38,0),
	GENERIC_PRODUCT_PACKAGING_CODE VARCHAR(255),
	PACKAGE_SIZE VARCHAR(255),
	PACKAGE_SIZE_UNIT_OF_MEASURE VARCHAR(255),
	PACKAGE_QUANTITY VARCHAR(255),
	UNIT_DOSE_UNIT_OF_USE_PACKAGE_CODE VARCHAR(255),
	PACKAGE_DESCRIPTION_CODE VARCHAR(255),
	GENERIC_PRODUCT_IDENTIFIER VARCHAR(255),
	TRANSACTION_CODE VARCHAR(255),
	LAST_CHANGE_DATE VARCHAR(255),
	RESERVE VARCHAR(255)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPAN_M25GPRR_GPPC_PRICE_REFERENCE (
	SOURCEFILEID NUMBER(38,0),
	SOURCEFILELINENUMBER NUMBER(38,0),
	GENERIC_PRODUCT_PACKAGING_CODE VARCHAR(255),
	GPPC_PRICE_CODE VARCHAR(255),
	GPPC_UNIT_PRICE VARCHAR(255),
	GPPC_EFF_DATE VARCHAR(255),
	TRANSACTION_CODE VARCHAR(255),
	RESERVE VARCHAR(255)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPAN_M25MOD_SUPPLEMENTAL_DATA (
	SOURCEFILEID NUMBER(38,0),
	SOURCEFILELINENUMBER NUMBER(38,0),
	MODIFIER_CODE VARCHAR(255),
	MODIFIER_DESCRIPTION VARCHAR(255),
	TRANSACTION_CODE VARCHAR(255),
	LASTCHANGEDATE VARCHAR(255),
	RESERVE VARCHAR(255)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPAN_M25NMOD_MODIFIER (
	SOURCEFILEID NUMBER(38,0),
	SOURCEFILELINENUMBER NUMBER(38,0),
	NDC_UPC_HRI VARCHAR(255),
	RESERVE_1 VARCHAR(255),
	MODIFIER_CODE VARCHAR(255),
	TRANSACTION_CODE VARCHAR(255),
	LASTCHANGEDATE VARCHAR(255),
	RESERVE_2 VARCHAR(255)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPAN_M25TCRF_THERAPEUTIC_CLASS (
	SOURCEFILEID NUMBER(38,0),
	SOURCEFILELINENUMBER NUMBER(38,0),
	THERAPEUTIC_CLASSIFICATION_CODE VARCHAR(255),
	RESERVE_1 VARCHAR(255),
	RECORD_TYPE_CODE VARCHAR(255),
	TC_GPI_NAME VARCHAR(255),
	RESERVE_2 VARCHAR(255),
	TRANSACTION_CODE VARCHAR(255),
	LASTCHANGEDATE VARCHAR(255)
);

create or replace TABLE KPH_VERTEX_PRD.STAGE.MEDISPAN_M25VAL_VALIDATION (
	SOURCEFILEID NUMBER(38,0),
	SOURCEFILELINENUMBER NUMBER(38,0),
	FIELD_IDENTIFIER VARCHAR(255),
	FIELD_VALUE VARCHAR(255),
	LANGUAGE_CODE VARCHAR(255),
	VALUE_DESCRIPTION VARCHAR(255),
	VALUE_ABBREVIATION VARCHAR(255),
	RESERVE VARCHAR(255)
);


CREATE OR REPLACE PROCEDURE KPH_VERTEX_PRD.STAGE.SPNONCORE_MEDISPAN_CODEHANDLER_MISCQUERIES("VREQUESTTYPE" NUMBER(38,0), "VFILELAYOUT" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    SP_NAME STRING DEFAULT 'MEDISPAN.SPNONCORE_MEDISPAN_CODEHANDLER_MISCQUERIES';
    SP_START_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
BEGIN

    -- ############################################################################################################
    -- REQUEST TYPE 1:
    -- Used to clear staging tables for a specific Medispan file layout.
    -- ############################################################################################################
    IF (VREQUESTTYPE = 1) THEN

        IF (VFILELAYOUT = 'M25') THEN
            TRUNCATE TABLE STAGE.MEDISPANAWPPRICES;
            TRUNCATE TABLE STAGE.MEDISPANCMSFULPRICES;
            TRUNCATE TABLE STAGE.MEDISPANGENERICPRODUCTS;
            TRUNCATE TABLE STAGE.MEDISPANINGREDIENTS;
            TRUNCATE TABLE STAGE.MEDISPANKEYIDENTIFIERS;
            TRUNCATE TABLE STAGE.MEDISPANMANUFACTURERNAMES;
            TRUNCATE TABLE STAGE.MEDISPANMANUFACTURERSDPMASTERS;
            TRUNCATE TABLE STAGE.MEDISPANNEWOLDNDCS;
            TRUNCATE TABLE STAGE.MEDISPANPACKAGINGEXTENSIONS;
            TRUNCATE TABLE STAGE.MEDISPANPACKAGINGS;
            TRUNCATE TABLE STAGE.MEDISPANPRODUCTNAMES;
            TRUNCATE TABLE STAGE.MEDISPANWACPRICES;

        ELSEIF (VFILELAYOUT = 'M25GPRR') THEN
            TRUNCATE TABLE STAGE.MEDISPAN_M25GPRR_GPPC_PRICE_REFERENCE;

        ELSEIF (VFILELAYOUT = 'M25NMOD') THEN
            TRUNCATE TABLE STAGE.MEDISPAN_M25NMOD_MODIFIER;

        ELSEIF (VFILELAYOUT = 'M25GPPC') THEN
            TRUNCATE TABLE STAGE.MEDISPAN_M25GPPC_GPPC;

        ELSEIF (VFILELAYOUT = 'M25MOD') THEN
            TRUNCATE TABLE STAGE.MEDISPAN_M25MOD_SUPPLEMENTAL_DATA;

        ELSEIF (VFILELAYOUT = 'M25TCRF') THEN
            TRUNCATE TABLE STAGE.MEDISPAN_M25TCRF_THERAPEUTIC_CLASS;
			
		ELSEIF (VFILELAYOUT = 'M25VAL') THEN
            TRUNCATE TABLE STAGE.MEDISPAN_M25VAL_VALIDATION;
			
		ELSEIF (VFILELAYOUT = 'M25DICT') THEN
            TRUNCATE TABLE STAGE.MEDISPAN_M25DICT_DICTIONARY;

        END IF;

    END IF;

    -- ############################################################################################################
    -- AUDITING
    -- ############################################################################################################
    INSERT INTO METRICS.SP_CALL
    (
        SP_NAME,
        SP_START_TIME,
        SP_USER,
        SP_END_TIME
    )
    VALUES
    (
        :SP_NAME,
        :SP_START_TIME,
        CURRENT_USER(),
        CURRENT_TIMESTAMP()
    );

    RETURN 'SUCCESS';

EXCEPTION
    WHEN OTHER THEN
	
        INSERT INTO METRICS.SP_CALL
        (
            SP_NAME,
            SP_START_TIME,
            SP_USER,
            SP_END_TIME
        )
        VALUES
        (
            :SP_NAME || ' - FAILED',
            :SP_START_TIME,
            CURRENT_USER(),
            CURRENT_TIMESTAMP()
        );

        RAISE;
END;
$$;

 /* ============================================================================
   MEDISPAN
   ============================================================================ */
create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_AWPPRICES start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_CMSFULPRICES start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_GENERICPRODUCTS start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_INGREDIENTS start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_KEYIDENTIFIERS start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_M25DICT_DICTIONARY start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_M25GPPC start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_M25GPRR_GPPC_PRICE_REFERENCE start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_M25MOD_SUPPLEMENTAL_DATA start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_M25NMOD_MODIFIER start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_M25TCRF_THERAPEUTIC_CLASS start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_M25VAL_VALIDATION start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_MANUFACTURERNAMES start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_MANUFACTURERSDPMASTERS start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_NEWOLDNDCS start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_PACKAGINGEXTENSIONS start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_PACKAGINGS start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_PRODUCTNAMES start with 1 increment by 1 noorder;

create or replace sequence KPH_VERTEX_PRD.MEDISPAN.SEQ_WACPRICES start with 1 increment by 1 noorder;

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.AWPPRICES (
	AWPPRICEID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_AWPPRICES.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	AWPINDICATORCODE VARCHAR(1),
	AWPPACKAGEPRICE NUMBER(10,2),
	AWPUNITPRICE NUMBER(13,5),
	EFFECTIVEDATE DATE,
	OLDERAWPPACKAGEPRICE NUMBER(10,2),
	OLDERAWPUNITPRICE NUMBER(13,5),
	OLDERAWPEFFECTIVEDATE DATE,
	RESERVE VARCHAR(16),
	LASTCHANGEDATE DATE,
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (AWPPRICEID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.CMSFULPRICES (
	CMSFULPRICEID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_CMSFULPRICES.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	RESERVE1 VARCHAR(1),
	CMSFULPRICE NUMBER(13,5),
	CMSFULPRICEEFFECTIVEDATE DATE,
	FIRSTOLDESTCMSFULPRICE NUMBER(13,5),
	FIRSTOLDESTCMDFULPRICEEFFECTIVEDATE DATE,
	SECONDOLDESTCMSFULPRICE NUMBER(13,5),
	SECONDOLDESTCMSFULPRICEEFFECTIVEDATE DATE,
	RESERVE2 VARCHAR(15),
	LASTCHANGEDATE DATE,
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (CMSFULPRICEID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.GENERICPRODUCTS (
	GENERICPRODUCTID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_GENERICPRODUCTS.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	GENERICPRODUCTIDENTIFIER VARCHAR(14),
	RESERVE VARCHAR(5),
	GPIGENERICNAME VARCHAR(60),
	LASTCHANGEDATE DATE,
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (GENERICPRODUCTID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.INGREDIENTS (
	INGREDIENTID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_INGREDIENTS.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	INGREDIENTGENERIDIDTYPECODE VARCHAR(1),
	INGREDIENTGENERICIDNUMBER VARCHAR(9),
	INGREDIENTSTRENGTH NUMBER(13,5),
	INGREDIENTUNITOFMEASURE VARCHAR(11),
	GENERICINGREDIENTNAME VARCHAR(40),
	ACTIVEINACTIVEINGREDIENTFLAG VARCHAR(4),
	RESERVE VARCHAR(4),
	LASTCHANGEDATE DATE,
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (INGREDIENTID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.KEYIDENTIFIERS (
	KEYIDENTIFIERID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_KEYIDENTIFIERS.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	SEQUENCECODE VARCHAR(7),
	LABELERCODE VARCHAR(5),
	GENERICIDTYPECODE VARCHAR(1),
	GENERICIDNUMBER VARCHAR(9),
	DEACLASSCODE VARCHAR(5),
	AFHSTHERAPEUTICCLASSCODE VARCHAR(6),
	ITEMSTATUSFLAG VARCHAR(1),
	LOCALSYSTEMATICFLAG VARCHAR(1),
	TEECODE VARCHAR(2),
	FORMATTEDIDNUMBER VARCHAR(13),
	RXOTCINDICATOR VARCHAR(1),
	THIRDPARTYRESTRICTIONCODE VARCHAR(1),
	MAINTENANCEDRUGCODE VARCHAR(1),
	DISPENSINGUNITCODE VARCHAR(1),
	UNITDOSECODE VARCHAR(1),
	ROUTEOFADMINISTRATION VARCHAR(2),
	FORMTYPECODE VARCHAR(1),
	DOLLARRANKCODE VARCHAR(1),
	RXRANKCODE VARCHAR(1),
	NUMBERSYSTEMCHARACTER VARCHAR(1),
	SECONDARYFORMATIDCODE VARCHAR(1),
	SECONDARYIDNUMBER VARCHAR(10),
	MULTISOURCECODE VARCHAR(1),
	BRANDNAMECODE VARCHAR(1),
	RESERVE1 VARCHAR(1),
	INTERNALEXTERNALCODE VARCHAR(1),
	SINGLECOMINATIONCODE VARCHAR(1),
	STORAGECONDITIONCODE VARCHAR(1),
	LIMITEDSTATIBILITYCODE VARCHAR(1),
	LASTCHANGEDATE DATE,
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (KEYIDENTIFIERID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.M25DICT_DICTIONARY (
	M25DICT_ID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_M25DICT_DICTIONARY.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	SOURCEFILELINENUMBER NUMBER(38,0),
	FIELD_IDENTIFIER VARCHAR(255),
	FIELD_VALUE VARCHAR(255),
	FIELD_TYPE VARCHAR(15),
	FIELD_LENGTH NUMBER(15,0),
	IMPLIED_DECIMAL_FLAG VARCHAR(1),
	DECIMAL_PLACES VARCHAR(5),
	FIELD_VALIDATION_FLAG VARCHAR(1),
	FIELD_ABBREVIATION_FLAG VARCHAR(1),
	RESERVE VARCHAR(255),
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (M25DICT_ID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.M25GPPC_GPPC (
	M25GPPC_ID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_M25GPPC.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	SOURCEFILELINENUMBER NUMBER(38,0),
	GENERIC_PRODUCT_PACKAGING_CODE VARCHAR(8),
	PACKAGE_SIZE NUMBER(8,3),
	PACKAGE_SIZE_UNIT_OF_MEASURE VARCHAR(2),
	PACKAGE_QUANTITY NUMBER(38,0),
	UNIT_DOSE_UNIT_OF_USE_PACKAGE_CODE VARCHAR(1),
	PACKAGE_DESCRIPTION_CODE VARCHAR(2),
	GENERIC_PRODUCT_IDENTIFIER VARCHAR(14),
	TRANSACTION_CODE VARCHAR(1),
	LAST_CHANGE_DATE DATE,
	RESERVE VARCHAR(15),
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (M25GPPC_ID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.M25GPRR_GPPC_PRICE_REFERENCE (
	M25GPRR_GPPC_PRICE_REFERENCE_ID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_M25GPRR_GPPC_PRICE_REFERENCE.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	SOURCEFILELINENUMBER NUMBER(38,0),
	GENERIC_PRODUCT_PACKAGING_CODE VARCHAR(8),
	GPPC_PRICE_CODE VARCHAR(1),
	GPPC_UNIT_PRICE NUMBER(13,5),
	GPPC_EFF_DATE DATE,
	TRANSACTION_CODE VARCHAR(1),
	RESERVE VARCHAR(5),
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (M25GPRR_GPPC_PRICE_REFERENCE_ID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.M25MOD_SUPPLEMENTAL_DATA (
	M25MOD_SUPPLEMENTAL_DATA_ID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_M25MOD_SUPPLEMENTAL_DATA.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	SOURCEFILELINENUMBER NUMBER(38,0),
	MODIFIER_CODE VARCHAR(6),
	MODIFIER_DESCRIPTION VARCHAR(25),
	TRANSACTION_CODE VARCHAR(1),
	LASTCHANGEDATE DATE,
	RESERVE VARCHAR(24),
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (M25MOD_SUPPLEMENTAL_DATA_ID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.M25NMOD_MODIFIER (
	M25NMOD_MODIFIER_ID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_M25NMOD_MODIFIER.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	SOURCEFILELINENUMBER NUMBER(38,0),
	NDC_UPC_HRI VARCHAR(11),
	RESERVE_1 VARCHAR(1),
	MODIFIER_CODE VARCHAR(6),
	TRANSACTION_CODE VARCHAR(1),
	LASTCHANGEDATE DATE,
	RESERVE_2 VARCHAR(5),
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (M25NMOD_MODIFIER_ID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.M25TCRF_THERAPEUTIC_CLASS (
	TCRFTHERAPEUTICCLASSID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_M25TCRF_THERAPEUTIC_CLASS.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	SOURCEFILELINENUMBER NUMBER(38,0),
	THERAPEUTIC_CLASSIFICATION_CODE VARCHAR(10),
	RESERVE_1 VARCHAR(4),
	RECORD_TYPE_CODE VARCHAR(1),
	TC_GPI_NAME VARCHAR(60),
	RESERVE_2 VARCHAR(19),
	TRANSACTION_CODE VARCHAR(1),
	LASTCHANGEDATE DATE,
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (TCRFTHERAPEUTICCLASSID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.M25VAL_VALIDATION (
	M25VAL_ID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_M25VAL_VALIDATION.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	SOURCEFILELINENUMBER NUMBER(38,0),
	FIELD_IDENTIFIER VARCHAR(50),
	FIELD_VALUE VARCHAR(50),
	LANGUAGE_CODE VARCHAR(30),
	VALUE_DESCRIPTION VARCHAR(255),
	VALUE_ABBREVIATION VARCHAR(255),
	RESERVE VARCHAR(255),
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (M25VAL_ID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.MANUFACTURERNAMES (
	MANUFACTURERNAMEID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_MANUFACTURERNAMES.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	MANUFACTURERSNAME VARCHAR(30),
	MANUFACTURERSABBREVIATEDNAME VARCHAR(10),
	PRODUCTDESCRIPTIONABBREVIATION VARCHAR(25),
	DRUGNAMECODE VARCHAR(6),
	GENERICPRODUCTPACKAGINGCODE VARCHAR(8),
	LASTCHANGEDATE DATE,
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (MANUFACTURERNAMEID)
);


create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.MANUFACTURERSDPMASTERS (
	MANUFACTURERSDPMASTERID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_MANUFACTURERSDPMASTERS.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	RESERVE VARCHAR(1),
	DPPACKAGEPRICE NUMBER(10,2),
	DPUNITPRICE NUMBER(13,5),
	EFFECTIVEDATE DATE,
	OLDERDPPACKAGEPRICE NUMBER(10,2),
	OLDERDPUNITPRICE NUMBER(13,5),
	OLDERDPEFFECTIVEDATE DATE,
	RESERVE2 VARCHAR(16),
	LASTCHANGEDATE DATE,
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (MANUFACTURERSDPMASTERID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.NEWOLDNDCS (
	NEWOLDNDCID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_NEWOLDNDCS.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	OLDNDC VARCHAR(11),
	RESERVE1 VARCHAR(1),
	OLDFORMATTEDIDNUMBER VARCHAR(13),
	OLDEFFECTIVEDATE DATE,
	NEWNDC VARCHAR(11),
	RESERVE2 VARCHAR(1),
	NEWFORMATTEDIDNUMBER VARCHAR(13),
	NEWEFFECTIVEDATE DATE,
	RESERVE3 VARCHAR(19),
	LASTCHANGEDATE DATE,
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (NEWOLDNDCID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.PACKAGINGEXTENSIONS (
	PACKAGINGEXTENSIONID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_PACKAGINGEXTENSIONS.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	METRICSTRENGTH NUMBER(13,5),
	STRENGTHUNITOFMEASURE VARCHAR(11),
	LIMITEDDISCRIBUTIONCODE VARCHAR(2),
	EXTENDEDAHFSTHERAPEUTICCLASSCODE VARCHAR(8),
	INACTIVEDATE DATE,
	RESERVE VARCHAR(37),
	LASTCHANGEDATE DATE,
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (PACKAGINGEXTENSIONID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.PACKAGINGS (
	PACKAGEID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_PACKAGINGS.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	RESERVE1 VARCHAR(23),
	DOSAGEFORM VARCHAR(4),
	PACKAGESIZE NUMBER(8,3),
	PACKAGESIZEUNITOFMEASURE VARCHAR(2),
	PACKAGEQUANTITY NUMBER(38,0),
	REPACKAGECODE VARCHAR(1),
	TOTALPACKAGEQUANTITY NUMBER(12,3),
	DESICODE VARCHAR(1),
	PACKAGEDESCRIPTION VARCHAR(10),
	RESERVE2 VARCHAR(6),
	NEXTSMALLERNDCSUFFIXNUMBER VARCHAR(2),
	NEXTLARGETNDCSUFFIXNUMBER VARCHAR(2),
	INNERPACKCODE VARCHAR(1),
	CLINICPACKCODE VARCHAR(1),
	RESERVE3 VARCHAR(1),
	LASTCHANGEDATE DATE,
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (PACKAGEID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.PRODUCTNAMES (
	PRODUCTNAMEID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_PRODUCTNAMES.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	PRODUCTNAME VARCHAR(25),
	PRODUCTNAMEEXTENSION VARCHAR(35),
	RESERVE1 VARCHAR(8),
	ALLERGYPATTERNCODE VARCHAR(4),
	RESERVE2 VARCHAR(2),
	PPGINDICATORCODE VARCHAR(1),
	HFPGINDICATORCODE VARCHAR(1),
	LABELERTYPECODE VARCHAR(1),
	PRICINGSPREADCODE VARCHAR(1),
	RESERVE3 VARCHAR(1),
	LASTCHANGEDATE DATE,
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (PRODUCTNAMEID)
);

create or replace TABLE KPH_VERTEX_PRD.MEDISPAN.WACPRICES (
	WACPRICEID NUMBER(38,0) NOT NULL DEFAULT KPH_VERTEX_PRD.MEDISPAN.SEQ_WACPRICES.NEXTVAL,
	SOURCEFILEID NUMBER(38,0),
	NDC VARCHAR(11),
	IDNUMBERFORMATCODE VARCHAR(1),
	RECORDCODE VARCHAR(3),
	TRANSACTIONCODE VARCHAR(1),
	RESERVE1 VARCHAR(1),
	WACPACKAGEPRICE NUMBER(10,2),
	WACUNITPRICE NUMBER(13,5),
	EFFECTIVEDATE DATE,
	OLDERWACPACKAGEPRICE NUMBER(10,2),
	OLDERWACUNITPRICE NUMBER(13,5),
	OLDERWACEFFECTIVEDATE DATE,
	RESERVE2 VARCHAR(16),
	LASTCHANGEDATE DATE,
	ENTEREDBY VARCHAR(75) DEFAULT CURRENT_USER(),
	ENTEREDTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (WACPRICEID)
);

CREATE OR REPLACE PROCEDURE KPH_VERTEX_PRD.MEDISPAN.SPNONCORE_MEDISPAN_CODEHANDLER("VSOURCEFILEID" NUMBER(38,0), "VFILELAYOUT" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    SP_START_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP();
    SP_NAME STRING DEFAULT 'Medispan.spNonCore_Medispan_Codehandler';
BEGIN

    -- ============================================================
    -- Main Logic
    -- ============================================================

    IF (vFileLayout = 'M25TCRF') THEN
        CALL Medispan.spNonCore_Medispan_Codehandler_M25TCRF(:vSourceFileID);

    ELSEIF (vFileLayout = 'M25MOD') THEN
        CALL Medispan.spNonCore_Medispan_Codehandler_M25MOD(:vSourceFileID);

    ELSEIF (vFileLayout = 'M25GPPC') THEN
        CALL Medispan.spNonCore_Medispan_Codehandler_M25GPPC(:vSourceFileID);

    ELSEIF (vFileLayout = 'M25NMOD') THEN
        CALL Medispan.spNonCore_Medispan_Codehandler_M25NMOD(:vSourceFileID);

    ELSEIF (vFileLayout = 'M25GPRR') THEN
        CALL Medispan.spNonCore_Medispan_Codehandler_M25GPRR(:vSourceFileID);
		
	ELSEIF (vFileLayout = 'M25DICT') THEN
        CALL Medispan.SPNONCORE_MEDISPAN_CODEHANDLER_M25DICT(:vSourceFileID);
	
	ELSEIF (vFileLayout = 'M25VAL') THEN
        CALL Medispan.SPNONCORE_MEDISPAN_CODEHANDLER_M25VAL(:vSourceFileID);

    ELSEIF (vFileLayout = 'M25') THEN
        CALL Medispan.spNonCore_Medispan_Codehandler_M25();

    END IF;

    -- ============================================================
    -- Logging
    -- ============================================================

    INSERT INTO METRICS.SP_CALL  
    (SP_NAME, SP_START_TIME, SP_USER, SP_END_TIME)
    VALUES (:SP_NAME, :SP_START_TIME, CURRENT_USER(), CURRENT_TIMESTAMP());

    RETURN 'SUCCESS';

-- ============================================================
-- Exception Handling
-- ============================================================

EXCEPTION
    WHEN OTHER THEN
        -- Log failure
        INSERT INTO METRICS.SP_CALL  
        (SP_NAME, SP_START_TIME, SP_USER, SP_END_TIME)
        VALUES (:SP_NAME, :SP_START_TIME, CURRENT_USER(), CURRENT_TIMESTAMP());

        RETURN 'FAILED: ' || SQLERRM;

END;
$$;

CREATE OR REPLACE PROCEDURE KPH_VERTEX_PRD.MEDISPAN.SPNONCORE_MEDISPAN_CODEHANDLER_M25()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
	SP_START_TIME TIMESTAMP := CURRENT_TIMESTAMP();
	SP_NAME VARCHAR := 'SPNONCORE_MEDISPAN_CODEHANDLER_M25';
BEGIN
MERGE INTO Medispan.KeyIdentifiers m
USING Stage.MedispanKeyIdentifiers s
ON m.NDC = s.NDC
AND m.SourceFileID = s.SourceFileID	
WHEN NOT MATCHED THEN
INSERT (
    SourceFileID,
    NDC,
    SequenceCode,
    LabelerCode,
    GenericIDTypeCode,
    GenericIDNumber,
    DEAClassCode,
    AFHSTherapeuticClassCode,
    ItemStatusFlag,
    LocalSystematicFlag,
    TEECode,
    FormattedIDNumber,
    RxOtcIndicator,
    ThirdPartyRestrictionCode,
    MaintenanceDrugCode,
    DispensingUnitCode,
    UnitDoseCode,
    RouteofAdministration,
    FormTypeCode,
    DollarRankCode,
    RxRankCode,
    NumberSystemCharacter,
    SecondaryFormatIDCode,
    SecondaryIDNumber,
    MultiSourceCode,
    BrandNameCode,
    Reserve1,
    InternalExternalCode,
    SingleCominationCode,
    StorageConditionCode,
    LimitedStatibilityCode,
    LastChangeDate
)
VALUES (
    s.SourceFileID,
    s.NDC,
    s.SequenceCode,
    s.LabelerCode,
    s.GenericIDTypeCode,
    s.GenericIDNumber,
    s.DEAClassCode,
    s.AFHSTherapeuticClassCode,
    s.ItemStatusFlag,
    s.LocalSystematicFlag,
    s.TEECode,
    s.FormattedIDNumber,
    s.RxOtcIndicator,
    s.ThirdPartyRestrictionCode,
    s.MaintenanceDrugCode,
    s.DispensingUnitCode,
    s.UnitDoseCode,
    s.RouteofAdministration,
    s.FormTypeCode,
    s.DollarRankCode,
    s.RxRankCode,
    s.NumberSystemCharacter,
    s.SecondaryFormatIDCode,
    s.SecondaryIDNumber,
    s.MultiSourceCode,
    s.BrandNameCode,
    s.Reserve1,
    s.InternalExternalCode,
    s.SingleCominationCode,
    s.StorageConditionCode,
    s.LimitedStatibilityCode,
    DATEADD(DAY,TO_NUMBER(RIGHT('20' || s.LastChangeDate, 3)) - 1,TO_DATE(LEFT('20' || s.LastChangeDate, 4), 'YYYY'))
);


MERGE INTO MEDISPAN.AWPPrices m
USING stage.medispanawpprices s
ON m.NDC = s.NDC AND
m.RECORDCODE=s.RECORDCODE
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN
INSERT
(		SourceFileID, 
		NDC, 
		IDNUMBERFORMATCODE,
		RECORDCODE,
		TRANSACTIONCODE,
		AWPIndicatorCode, 
		AWPPAckagePrice, 
		AWPUnitPrice, 
		EffectiveDate, 
		OlderAWPPackagePrice, 
		OlderAWPUnitPrice, 
		OlderAWPEffectiveDate, 
		Reserve, 
		LastChangeDate
)
VALUES
(
s.SourceFileID,
		s.NDC,
		s.IDNUMBERFORMATCODE,
		s.RECORDCODE,
		s.TRANSACTIONCODE,
		s.AWPIndicatorCode,
		CAST(s.AWPPAckagePrice AS BIGINT) * 0.01  ,
		CAST(s.AWPUnitPrice AS BIGINT) * 0.00001  ,
		TO_DATE(s.EffectiveDate,'YYYYMMDD')  ,
		CAST(s.OlderAWPPackagePrice AS BIGINT) * 0.01  ,
		CAST(s.OlderAWPUnitPrice AS BIGINT) * 0.00001  ,
		TO_DATE(s.OlderAWPEffectiveDate,'YYYYMMDD'),
		s.Reserve,
		DATEADD(DAY,TO_NUMBER(RIGHT('20' || s.LastChangeDate, 3)) - 1,TO_DATE(LEFT('20' || s.LastChangeDate, 4), 'YYYY'))  
);


MERGE INTO Medispan.CMSFULPrices m
USING Stage.MedispanCMSFULPrices s
ON m.NDC = s.NDC
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN
INSERT
            (
                SourceFileID, 
                NDC,
				IDNUMBERFORMATCODE,
				RECORDCODE,
				TRANSACTIONCODE,
                Reserve1, 
                CMSFULprice, 
                CMSFULPriceEffectiveDate, 
                FirstOldestCMSFULPrice, 
                FirstOldestCMDFULPriceEffectiveDate, 
                SecondOldestCMSFULPrice, 
                SecondOldestCMSFULPriceEffectiveDate, 
                Reserve2, 
                LastChangeDate
            )
VALUES 
            (       s.SourceFileID,
                    s.NDC,
					IDNUMBERFORMATCODE,
					RECORDCODE,
					TRANSACTIONCODE,
                    s.Reserve1,
                    CAST(s.CMSFULprice AS BIGINT) * 0.00001,
                    TO_DATE(s.CMSFULPriceEffectiveDate,'YYYYMMDD'),
                    CAST(s.FirstOldestCMSFULPrice AS BIGINT) * 0.00001,
                    TO_DATE(s.FirstOldestCMDFULPriceEffectiveDate,'YYYYMMDD'),
                    CAST(s.SecondOldestCMSFULPrice AS BIGINT) * 0.00001,
                    TO_DATE(s.SecondOldestCMSFULPriceEffectiveDate,'YYYYMMDD'),
                    s.Reserve2,
                    DATEADD(DAY,TO_NUMBER(RIGHT('20' || s.LastChangeDate, 3)) - 1,TO_DATE(LEFT('20' || s.LastChangeDate, 4), 'YYYY'))
                );
				

MERGE INTO Medispan.GenericProducts m
USING Stage.MedispanGenericProducts s
ON m.NDC = s.NDC
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN 
INSERT
		(
			SourceFileID, 
			NDC,
			IDNUMBERFORMATCODE,
			RECORDCODE,
			TRANSACTIONCODE,
			GenericProductIdentifier, 
			Reserve, 
			GPIGenericName, 
			LastChangeDate
		)
VALUES
		(
			s.SourceFileID,
			s.NDC,
			IDNUMBERFORMATCODE,
			RECORDCODE,
			TRANSACTIONCODE,
			s.GenericProductIdentifier,
			s.Reserve,
			s.GPIGenericName,
			DATEADD(DAY,TO_NUMBER(RIGHT('20' || s.LastChangeDate, 3)) - 1,TO_DATE(LEFT('20' || s.LastChangeDate, 4), 'YYYY'))
		);
		

MERGE INTO Medispan.Ingredients m
USING Stage.MedispanIngredients s
ON m.NDC = s.NDC 
AND m.RECORDCODE = s.RECORDCODE
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN 
INSERT
		(
			SourceFileID, 
			NDC,
			IDNUMBERFORMATCODE,
			RECORDCODE,
			TRANSACTIONCODE,
			IngredientGeneridIDTypeCode, 
			IngredientGenericIDNumber, 
			IngredientStrength, 
			IngredientUnitofMeasure, 
			GenericIngredientName, 
			ActiveInactiveIngredientFlag, 
			Reserve, 
			LastChangeDate
		)
VALUES
		(
			s.SourceFileID,
			s.NDC,
			IDNUMBERFORMATCODE,
			RECORDCODE,
			TRANSACTIONCODE,
			s.IngredientGeneridIDTypeCode,
			s.IngredientGenericIDNumber,
			CAST(s.IngredientStrength AS BIGINT) * 0.00001,
			s.IngredientUnitofMeasure,
			s.GenericIngredientName,
			s.ActiveInactiveIngredientFlag,
			s.Reserve,
			DATEADD(DAY,TO_NUMBER(RIGHT('20' || s.LastChangeDate, 3)) - 1,TO_DATE(LEFT('20' || s.LastChangeDate, 4), 'YYYY'))
		);
		

MERGE INTO Medispan.ManufacturerNames m
USING Stage.MedispanManufacturerNames s
ON s.NDC = m.NDC
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN 
INSERT 
		(
			SourceFileID, 
			NDC,
			IDNUMBERFORMATCODE,
			RECORDCODE,
			TRANSACTIONCODE,
			ManufacturersName, 
			ManufacturersAbbreviatedName, 
			ProductDescriptionAbbreviation, 
			DrugNameCode, 
			GenericProductPackagingCode, 
			LastChangeDate
		)
VALUES 
		(
			s.SourceFileID,
			s.NDC,
			IDNUMBERFORMATCODE,
			RECORDCODE,
			TRANSACTIONCODE,
			s.ManufacturersName,
			s.ManufacturersAbbreviatedName,
			s.ProductDescriptionAbbreviation,
			s.DrugNameCode,
			s.GenericProductPackagingCode,
			DATEADD(DAY,TO_NUMBER(RIGHT('20' || s.LastChangeDate, 3)) - 1,TO_DATE(LEFT('20' || s.LastChangeDate, 4), 'YYYY'))
		);
		

MERGE INTO Medispan.ManufacturersDPMasters m
USING Stage.MedispanManufacturersDPMasters s
ON m.NDC = s.NDC 
AND m.RECORDCODE = s.RECORDCODE
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN
INSERT
		(
			SourceFileID, 
			NDC,
			IDNUMBERFORMATCODE,
			RECORDCODE,
			TRANSACTIONCODE,
			Reserve, 
			DPPackagePrice, 
			DPUnitPrice, 
			EffectiveDate, 
			OlderDPPackagePrice, 
			OlderDPUnitPrice, 
			OlderDPEffectiveDate,
			Reserve2, 
			LastChangeDate
		)
VALUES
		(
			s.SourceFileID,
			s.NDC,
			IDNUMBERFORMATCODE,
			RECORDCODE,
			TRANSACTIONCODE,
			s.Reserve,
			CAST(s.DPPackagePrice AS BIGINT) * 0.01,
			CAST(s.DPUnitPrice AS BIGINT) * 0.00001,
			TO_DATE(s.EffectiveDate,'YYYYMMDD'),
			CAST(s.OlderDPPackagePrice AS BIGINT) * 0.01,
			CAST(s.OlderDPUnitPrice AS BIGINT) * 0.00001,
			TO_DATE(s.OlderDPEffectiveDate, 'YYYYMMDD'),
			s.Reserve2,
			DATEADD(DAY,TO_NUMBER(RIGHT('20' || s.LastChangeDate, 3)) - 1,TO_DATE(LEFT('20' || s.LastChangeDate, 4), 'YYYY'))
		);
		

MERGE INTO Medispan.NewOldNDCs m
USING Stage.MedispanNewOldNDCs s
ON s.NDC = m.NDC
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN
INSERT 
		(
			SourceFileID, 
			NDC, 
			OldNDC, 
			Reserve1, 
			OldFormattedIDNumber, 
			OldEffectiveDate, 
			NewNDC, 
			Reserve2, 
			NewFormattedIDNumber, 
			NewEffectiveDate, 
			Reserve3, 
			LastChangeDate
		)
VALUES
		(
			s.SourceFileID,
			s.NDC,
			s.OldNDC,
			s.Reserve1,
			s.OldFormattedIDNumber,
			DATEADD(DAY,TO_NUMBER(RIGHT('20' || s.OldEffectiveDate, 3)) - 1,TO_DATE(LEFT('20' || s.OldEffectiveDate, 4), 'YYYY')),
			s.NewNDC,
			s.Reserve2,
			s.NewFormattedIDNumber,
			DATEADD(DAY,TO_NUMBER(RIGHT('20' || s.NewEffectiveDate, 3)) - 1,TO_DATE(LEFT('20' || s.NewEffectiveDate, 4), 'YYYY')),
			s.Reserve3,
			DATEADD(DAY,TO_NUMBER(RIGHT('20' || s.LastChangeDate, 3)) - 1,TO_DATE(LEFT('20' || s.LastChangeDate, 4), 'YYYY'))
		);
		

MERGE INTO Medispan.PackagingExtensions m
USING Stage.MedispanPackagingExtensions s
ON s.NDC = m.NDC
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN
INSERT 
		(
			SourceFileID, 
			NDC,
			IDNUMBERFORMATCODE,
			RECORDCODE,
			TRANSACTIONCODE,
			MetricStrength, 
			StrengthUnitofMeasure, 
			LimitedDiscributionCode, 
			ExtendedAHFSTherapeuticClassCode, 
			InactiveDate, 
			Reserve, 
			LastChangeDate
		)
VALUES
		(
			s.SourceFileID,
			s.NDC,
			IDNUMBERFORMATCODE,
			RECORDCODE,
			TRANSACTIONCODE,
			CAST(s.MetricStrength AS BIGINT) * 0.00001,
			s.StrengthUnitofMeasure,
			s.LimitedDiscributionCode,
			s.ExtendedAHFSTherapeuticClassCode,
			TO_DATE(s.InactiveDate,'YYYYMMDD'),
			s.Reserve,
			DATEADD(DAY,TO_NUMBER(RIGHT('20' || s.LastChangeDate, 3)) - 1,TO_DATE(LEFT('20' || s.LastChangeDate, 4), 'YYYY'))
		);
		

MERGE INTO Medispan.Packagings m
USING Stage.MedispanPackagings s
ON s.NDC = m.NDC
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN
INSERT 
		( 
			SourceFileID, 
			NDC,
			IDNUMBERFORMATCODE,
			RECORDCODE,
			TRANSACTIONCODE,
			Reserve1, 
			DosageForm, 
			PackageSize, 
			PackageSizeUnitofMeasure, 
			PackageQuantity, 
			RepackageCode, 
			TotalPackageQuantity, 
			DESICode, 
			PackageDescription, 
			Reserve2, 
			NextSmallerNDCSuffixNumber,
			NextLargetNDCSuffixNumber, 
			InnerpackCode, 
			ClinicPackCode, 
			Reserve3, 
			LastChangeDate
		)
VALUES
		(
			s.SourceFileID,
			s.NDC,
			s.IDNUMBERFORMATCODE,
			s.RECORDCODE,
			s.TRANSACTIONCODE,
			s.Reserve1,
			s.DosageForm,
			CAST(s.PackageSize AS BIGINT) * 0.001,
			s.PackageSizeUnitofMeasure,
			CAST(s.PackageQuantity AS INT),
			s.RepackageCode,
			CAST(s.TotalPackageQuantity AS BIGINT) * 0.001,
			s.DESICode,
			s.PackageDescription,
			s.Reserve2,
			s.NextSmallerNDCSuffixNumber,
			s.NextLargetNDCSuffixNumber,
			s.InnerpackCode,
			s.ClinicPackCode,
			s.Reserve3,
			DATEADD(DAY,TO_NUMBER(RIGHT('20' || s.LastChangeDate, 3)) - 1,TO_DATE(LEFT('20' || s.LastChangeDate, 4), 'YYYY'))
		);
		

MERGE INTO Medispan.ProductNames m
USING Stage.MedispanProductNames s
ON s.NDC = m.NDC
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN
INSERT 
		(
			SourceFileID, 
			NDC, 
			IDNUMBERFORMATCODE,
			RECORDCODE,
			TRANSACTIONCODE,
			ProductName, 
			ProductNameExtension, 
			Reserve1, 
			AllergyPatternCode, 
			Reserve2, 
			PPGIndicatorCode, 
			HFPGIndicatorCode, 
			LabelerTypeCode, 
			PricingSpreadCode, 
			Reserve3, 
			LastChangeDate
		)
VALUES 
		(
			s.SourceFileID,
			s.NDC,
			IDNUMBERFORMATCODE,
			RECORDCODE,
			TRANSACTIONCODE,
			s.ProductName,
			s.ProductNameExtension,
			s.Reserve1,
			s.AllergyPatternCode,
			s.Reserve2,
			s.PPGIndicatorCode,
			s.HFPGIndicatorCode,
			s.LabelerTypeCode,
			s.PricingSpreadCode,
			s.Reserve3,
			DATEADD(DAY,TO_NUMBER(RIGHT('20' || s.LastChangeDate, 3)) - 1,TO_DATE(LEFT('20' || s.LastChangeDate, 4), 'YYYY'))
		);
		

MERGE INTO Medispan.WACPrices m
USING Stage.MedispanWACPrices s
ON s.NDC = m.NDC 
AND s.RECORDCODE = m.RECORDCODE
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN
INSERT 
		(
			SourceFileID, 
			NDC,
			IDNUMBERFORMATCODE,
			RECORDCODE,
			TRANSACTIONCODE,
			Reserve1, 
			WACPackagePrice, 
			WACUnitPrice, 
			EffectiveDate, 
			OlderWACPackagePrice, 
			OlderWACUnitPrice, 
			OlderWACEffectiveDate, 
			Reserve2, 
			LastChangeDate
		)
VALUES 
		(
			s.SourceFileID,
			s.NDC,
			s.IDNUMBERFORMATCODE,
			s.RECORDCODE,
			s.TRANSACTIONCODE,
			s.Reserve1,
			CAST(s.WACPackagePrice AS BIGINT) * 0.01,
			CAST(s.WACUnitPrice AS BIGINT) * 0.00001,
			TO_DATE(s.EffectiveDate,'YYYYMMDD'),
			CAST(s.OlderWACPackagePrice AS BIGINT) * 0.01,
			CAST(s.OlderWACUnitPrice AS BIGINT) * 0.00001,
			TO_DATE(s.OlderWACEffectiveDate, 'YYYYMMDD'),
			s.Reserve2,
			DATEADD(DAY,TO_NUMBER(RIGHT('20' || s.LastChangeDate, 3)) - 1,TO_DATE(LEFT('20' || s.LastChangeDate, 4), 'YYYY'))
		);
		
		--#####################################################################
    -- LOGGING
    --#####################################################################
    INSERT INTO METRICS.SP_CALL
    (
        SP_NAME,
        SP_START_TIME,
        SP_USER,
        SP_END_TIME
    )
    VALUES
    (
        :SP_NAME,
        :SP_START_TIME,
        CURRENT_USER(),
        CURRENT_TIMESTAMP()
    );

    RETURN 'SUCCESS';

EXCEPTION
    WHEN OTHER THEN
RETURN 'FAILED: ' || SQLERRM;
	
END;
$$;

CREATE OR REPLACE PROCEDURE KPH_VERTEX_PRD.MEDISPAN.SPNONCORE_MEDISPAN_CODEHANDLER_M25DICT("SOURCEFILEID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
		SP_START_TIME TIMESTAMP := CURRENT_TIMESTAMP();
		SP_NAME VARCHAR := 'SPNONCORE_MEDISPAN_CODEHANDLER_M25DICT';
BEGIN
MERGE INTO Medispan.M25DICT_Dictionary m
USING Stage.Medispan_M25DICT_Dictionary s
ON m.FIELD_IDENTIFIER = s.FIELD_IDENTIFIER
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN
INSERT
		(
			SourceFileID, 
			SourceFileLineNumber,
			Field_Identifier,
			Field_Value,
			Field_Type,
			Field_Length,
			Implied_Decimal_Flag,
			Decimal_Places,
			Field_Validation_Flag,
			Field_Abbreviation_Flag,
			Reserve
		)
VALUES
		(
			:SourceFileID,
			s.SourceFileLineNumber,
			s.Field_Identifier,
			s.Field_Value,
			s.Field_Type,
			s.Field_Length,
			s.Implied_Decimal_Flag,
			s.Decimal_Places,
			s.Field_Validation_Flag,
			s.Field_Abbreviation_Flag,
			s.Reserve
		);
		
--#####################################################################
    -- LOGGING
    --#####################################################################
    INSERT INTO METRICS.SP_CALL
    (
        SP_NAME,
        SP_START_TIME,
        SP_USER,
        SP_END_TIME
    )
    VALUES
    (
        :SP_NAME,
        :SP_START_TIME,
        CURRENT_USER(),
        CURRENT_TIMESTAMP()
    );

    RETURN 'SUCCESS';

EXCEPTION
    WHEN OTHER THEN
RETURN 'FAILED: ' || SQLERRM;
		
END;
$$;

CREATE OR REPLACE PROCEDURE KPH_VERTEX_PRD.MEDISPAN.SPNONCORE_MEDISPAN_CODEHANDLER_M25GPPC("SOURCEFILEID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS 
$$
DECLARE
		SP_START_TIME DATETIME DEFAULT GETDATE();
		SP_NAME VARCHAR := 'SPNONCORE_MEDISPAN_CODEHANDLER_M25GPPC';
BEGIN
MERGE INTO Medispan.M25GPPC_GPPC m
USING Stage.Medispan_M25GPPC_GPPC s
ON m.Generic_Product_Packaging_Code = s.Generic_Product_Packaging_Code
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN
INSERT
		(
			SourceFileID, 
			SourceFileLineNumber, 
			Generic_Product_Packaging_Code, 
			Package_Size, 
			Package_Size_Unit_of_Measure, 
			Package_Quantity,
			Unit_Dose_Unit_of_Use_Package_Code, 
			Package_Description_Code, 
			Generic_Product_Identifier, 
			Transaction_Code, 
			Last_Change_Date, 
			Reserve
		)
VALUES
		(
			SourceFileID,
			s.SourceFileLineNumber,
			s.Generic_Product_Packaging_Code,
			CAST(CAST(NULLIF(s.PACKAGE_SIZE, '') AS NUMBER(8,0)) / 1000 AS NUMBER(8,3)),
			s.Package_Size_Unit_of_Measure,
			s.Package_Quantity,
			s.Unit_Dose_Unit_of_Use_Package_Code,
			s.Package_Description_Code,
			s.Generic_Product_Identifier,
			s.Transaction_Code,
			TO_DATE(s.LAST_CHANGE_DATE, 'YYYYMMDD'),
			s.Reserve
		);
		
--#####################################################################
    -- LOGGING
    --#####################################################################
    INSERT INTO METRICS.SP_CALL
    (
        SP_NAME,
        SP_START_TIME,
        SP_USER,
        SP_END_TIME
    )
    VALUES
    (
        :SP_NAME,
        :SP_START_TIME,
        CURRENT_USER(),
        CURRENT_TIMESTAMP()
    );

    RETURN 'SUCCESS';

EXCEPTION
    WHEN OTHER THEN
RETURN 'FAILED: ' || SQLERRM;
		
END;
$$;

CREATE OR REPLACE PROCEDURE KPH_VERTEX_PRD.MEDISPAN.SPNONCORE_MEDISPAN_CODEHANDLER_M25GPRR("SOURCEFILEID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
		SP_START_TIME DATETIME DEFAULT GETDATE();
		SP_NAME VARCHAR := 'SPNONCORE_MEDISPAN_CODEHANDLER_M25GPRR';
BEGIN
MERGE INTO Medispan.M25GPRR_GPPC_Price_Reference m
USING Stage.Medispan_M25GPRR_GPPC_Price_Reference s
ON COALESCE(m.Generic_Product_Packaging_Code, '') = COALESCE(s.Generic_Product_Packaging_Code, '')
AND COALESCE(m.GPPC_PRICE_CODE, -1) = COALESCE(s.GPPC_PRICE_CODE, -1) 
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN
INSERT
(
    SourceFileID, 
    SourceFileLineNumber, 
    Generic_Product_Packaging_Code, 
    GPPC_Price_Code, 
    GPPC_Unit_Price, 
    GPPC_Eff_Date, 
    Transaction_Code, 
    Reserve
)
VALUES
(
    :SourceFileID,
    s.SourceFileLineNumber,
    s.Generic_Product_Packaging_Code,
    s.GPPC_Price_Code,
    CAST(
        TRY_TO_NUMBER(NULLIF(TRIM(s.GPPC_Unit_Price), ''), 13, 0) / 100000.0
        AS NUMERIC(13,5)
    ),
    TO_DATE(s.GPPC_Eff_Date, 'YYYYMMDD'),
    s.Transaction_Code,
    s.Reserve
);

--#####################################################################
    -- LOGGING
    --#####################################################################
    INSERT INTO METRICS.SP_CALL
    (
        SP_NAME,
        SP_START_TIME,
        SP_USER,
        SP_END_TIME
    )
    VALUES
    (
        :SP_NAME,
        :SP_START_TIME,
        CURRENT_USER(),
        CURRENT_TIMESTAMP()
    );

    RETURN 'SUCCESS';

EXCEPTION
    WHEN OTHER THEN
RETURN 'FAILED: ' || SQLERRM;

END;
$$;

CREATE OR REPLACE PROCEDURE KPH_VERTEX_PRD.MEDISPAN.SPNONCORE_MEDISPAN_CODEHANDLER_M25MOD("SOURCEFILEID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
		SP_START_TIME TIMESTAMP := CURRENT_TIMESTAMP();
		SP_NAME VARCHAR := 'SPNONCORE_MEDISPAN_CODEHANDLER_M25MOD';
BEGIN
MERGE INTO Medispan.M25MOD_Supplemental_Data m
USING Stage.Medispan_M25MOD_Supplemental_Data s
ON m.Modifier_Code = s.Modifier_Code
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN
INSERT
		(
			SourceFileID, 
			SourceFileLineNumber, 
			Modifier_Code, 
			Modifier_Description, 
			Transaction_Code, 
			LastChangeDate, 
			Reserve
		)
VALUES
		(
			:SOURCEFILEID,
			s.SourceFileLineNumber,
			s.Modifier_Code,
			s.Modifier_Description,
			s.Transaction_Code,
			TO_DATE(s.LastChangeDate,'YYYYMMDD'),
			s.Reserve
		);
		
--#####################################################################
    -- LOGGING
    --#####################################################################
    INSERT INTO METRICS.SP_CALL
    (
        SP_NAME,
        SP_START_TIME,
        SP_USER,
        SP_END_TIME
    )
    VALUES
    (
        :SP_NAME,
        :SP_START_TIME,
        CURRENT_USER(),
        CURRENT_TIMESTAMP()
    );

    RETURN 'SUCCESS';

EXCEPTION
    WHEN OTHER THEN
RETURN 'FAILED: ' || SQLERRM;

END;
$$;

CREATE OR REPLACE PROCEDURE KPH_VERTEX_PRD.MEDISPAN.SPNONCORE_MEDISPAN_CODEHANDLER_M25NMOD("SOURCEFILEID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
		SP_START_TIME TIMESTAMP := CURRENT_TIMESTAMP();
		SP_NAME VARCHAR := 'SPNONCORE_MEDISPAN_CODEHANDLER_M25NMOD';
BEGIN
MERGE INTO Medispan.M25NMOD_Modifier m
USING Stage.Medispan_M25NMOD_Modifier s
ON m.Modifier_Code = s.Modifier_Code
AND m.NDC_UPC_HRI = s.NDC_UPC_HRI
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN
INSERT
		(
			SourceFileID,
			SourceFileLineNumber, 
			NDC_UPC_HRI, 
			Reserve_1, 
			Modifier_Code, 
			Transaction_Code, 
			LastChangeDate, 
			Reserve_2
		)
VALUES
		(
			:SOURCEFILEID,
			s.SourceFileLineNumber,
			s.NDC_UPC_HRI,
			s.Reserve_1,
			s.Modifier_Code,
			s.Transaction_Code,
			TO_DATE(s.LastChangeDate,'YYYYMMDD'),
			s.Reserve_2
		);
		
--#####################################################################
    -- LOGGING
    --#####################################################################
    INSERT INTO METRICS.SP_CALL
    (
        SP_NAME,
        SP_START_TIME,
        SP_USER,
        SP_END_TIME
    )
    VALUES
    (
        :SP_NAME,
        :SP_START_TIME,
        CURRENT_USER(),
        CURRENT_TIMESTAMP()
    );

    RETURN 'SUCCESS';

EXCEPTION
    WHEN OTHER THEN
RETURN 'FAILED: ' || SQLERRM;

END;
$$;

CREATE OR REPLACE PROCEDURE KPH_VERTEX_PRD.MEDISPAN.SPNONCORE_MEDISPAN_CODEHANDLER_M25TCRF("SOURCEFILEID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
		SP_START_TIME TIMESTAMP := CURRENT_TIMESTAMP();
		SP_NAME VARCHAR := 'SPNONCORE_MEDISPAN_CODEHANDLER_M25TCRF';
BEGIN
MERGE INTO Medispan.M25TCRF_Therapeutic_Class m
USING Stage.Medispan_M25TCRF_Therapeutic_Class s
ON m.Therapeutic_Classification_Code = s.Therapeutic_Classification_Code
AND m.Record_Type_Code = s.Record_Type_Code
WHEN NOT MATCHED THEN
INSERT
		(
			SourceFileID, 
			SourceFileLineNumber, 
			Therapeutic_Classification_Code, 
			Reserve_1, 
			Record_Type_Code, 
			TC_GPI_Name,
			Reserve_2, 
			Transaction_Code, 
			LastChangeDate
		)
VALUES
		(
			:SOURCEFILEID,
			s.SourceFileLineNumber,
			s.Therapeutic_Classification_Code,
			s.Reserve_1,
			s.Record_Type_Code,
			s.TC_GPI_Name,
			s.Reserve_2,
			s.Transaction_Code,
			DATEADD(DAY,TO_NUMBER(RIGHT('20' || s.LastChangeDate, 3)) - 1,TO_DATE(LEFT('20' || s.LastChangeDate, 4), 'YYYY')) 
		);
		
--#####################################################################
    -- LOGGING
    --#####################################################################
    INSERT INTO METRICS.SP_CALL
    (
        SP_NAME,
        SP_START_TIME,
        SP_USER,
        SP_END_TIME
    )
    VALUES
    (
        :SP_NAME,
        :SP_START_TIME,
        CURRENT_USER(),
        CURRENT_TIMESTAMP()
    );

    RETURN 'SUCCESS';

EXCEPTION
    WHEN OTHER THEN
RETURN 'FAILED: ' || SQLERRM;

END;
$$;

CREATE OR REPLACE PROCEDURE KPH_VERTEX_PRD.MEDISPAN.SPNONCORE_MEDISPAN_CODEHANDLER_M25VAL("SOURCEFILEID" NUMBER(38,0))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
		SP_START_TIME TIMESTAMP := CURRENT_TIMESTAMP();
		SP_NAME VARCHAR := 'SPNONCORE_MEDISPAN_CODEHANDLER_M25VAL';
BEGIN
MERGE INTO Medispan.M25VAL_Validation m
USING Stage.Medispan_M25VAL_Validation s
ON m.FIELD_IDENTIFIER = s.FIELD_IDENTIFIER
AND m.FIELD_VALUE = s.FIELD_VALUE
AND m.SourceFileID = s.SourceFileID
WHEN NOT MATCHED THEN
INSERT
		(
			SourceFileID, 
			SourceFileLineNumber,
			Field_Identifier,
			Field_Value,
			Language_Code,
			Value_Description,
			Value_Abbreviation,
			Reserve
		)
VALUES
		(
			:SOURCEFILEID,
			s.SourceFileLineNumber,
			s.Field_Identifier,
			s.Field_Value,
			s.Language_Code,
			s.Value_Description,
			s.Value_Abbreviation,
			s.Reserve
		);
		
--#####################################################################
    -- LOGGING
    --#####################################################################
    INSERT INTO METRICS.SP_CALL
    (
        SP_NAME,
        SP_START_TIME,
        SP_USER,
        SP_END_TIME
    )
    VALUES
    (
        :SP_NAME,
        :SP_START_TIME,
        CURRENT_USER(),
        CURRENT_TIMESTAMP()
    );

    RETURN 'SUCCESS';

EXCEPTION
    WHEN OTHER THEN
RETURN 'FAILED: ' || SQLERRM;
		
END;
$$;



